### PR TITLE
Add some english names for Tingle Tuner-related actors

### PR DESCRIPTION
**Pull request by azer67**
agbR are secret item drops. Hover over them with the tuner cursor to make an exclamation mark appear and press A to reveal an item.
agbB are areas that restrict some tuner item uses (generally tingle bombs).
agbD are areas where the cursor gets stuck. If you go through the cursor with Link you gain a reward.

### CODE REVIEW

**Comment by LagoLunatic** [comment]
Thanks, this is helpful. Now that I know what they are I can find what their parameters do a lot easier, e.g. I already found agbR and agbD's parameter for what item to drop. Also, agbA seems to be hints you trigger with the A button and agbCSW seems to be hints that trigger automatically if you stand inside it for a while. Gonna work on implementing those and other params.

Any guesses as to what the remaining ones are? agbAT agbMARK agbA2 agbF2 agbF agbMW agbFA

**Comment by azer67** [comment]
I can take a look tomorrow, one of them seemed to be the pages of the legend of the fairy in TotG. One might be the tuner-only light rings in the ocean. Not sure about the rest, there are various text triggers I don't know well.

**Comment by azer67** [comment]
agbF2 are pages of the legend of the fairy (in Tower of the Gods).
agbF and agbFA seems to be tingle text that appears spontaneously when walking over the area. I don't understand the difference.
agbMARK seem to be dot markers on the map, and there's a text associated to it.
agbA2 is a text trigger you need to press A for with the cursor over it, just like agbA, except it seems to be marked on your map with a question mark?

Tingle Tuner-only light rings are actually just actor SwSlvg, which is named Gunboat/Big Octo Salvage Point in Winditor.

**Comment by LagoLunatic** [comment]
How do you actually trigger the legend of the fairy thing to start? I can't seem to read any of them with the tingle tuner, including the ones shown in [this video](https://www.youtube.com/watch?v=XiIW1Bq3tWk).

**Comment by azer67** [comment]
The video shows the legend of the fairy texts that appear only after you collect them in the dungeon. agbF2 is for collecting these pages. There are 5 of them to collect, I made pictures for where they are here: https://imgur.com/a/KFfQLED

**Pull request closed without merging**
